Fix image config type errors
Fixes the following errors:
- src/utils/imageConfigUtils.ts(2,10): error TS2459: Module '"@/data/types/project"' declares 'ImageConfig' locally, but it is not exported.
- src/utils/imageConfigUtils.ts(20,24): error TS2339: Property 'beforeHeader' does not exist on type 'unknown'.
- src/utils/imageConfigUtils.ts(24,34): error TS2339: Property 'beforeHeader' does not exist on type 'unknown'.
- src/utils/imageConfigUtils.ts(27,24): error TS2339: Property 'afterHeader' does not exist on type 'unknown'.
- src/utils/imageConfigUtils.ts(31,34): error TS2339: Property 'afterHeader' does not exist on type 'unknown'.